export const STORAGE_ACTIVITY_START_TIME = 'ACTIVITY_START_TIME'
export const STORAGE_ACTIVITIES = 'ACTIVITIES'
export const STORAGE_CATEGORIES = 'CATEGORIES'

export const STORAGE_CURRENT_ACTIVITY_ID = 'CURRENT_ACTIVITY_ID'

export const STORAGE_ACTIVITIES_LOG = 'ACTIVITIES_LOG'